/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto;

import Projeto.Funcionario.HomePageFuncionario;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Marques
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        caixaDeTxtUsuario = new javax.swing.JTextField();
        btLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        caixaDeTxtSenha = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Logo restaurante.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Restaurante");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 150, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/SideTab imagem.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 580));

        caixaDeTxtUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caixaDeTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeTxtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(caixaDeTxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 240, 50));

        btLogin.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btLogin.setText("LOGIN");
        btLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 90, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("SENHA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 80, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("USUÁRIO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 80, 30));

        caixaDeTxtSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caixaDeTxtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeTxtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(caixaDeTxtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 240, 50));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 300, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaDeTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeTxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaDeTxtUsuarioActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
           
            String usuario = caixaDeTxtUsuario.getText();
            String senha = caixaDeTxtSenha.getText();
            
            Statement stm = con.createStatement();
            
            String sql = "select * from login where usuario='" +usuario+"' and senha='"+senha+"'";
            String sql2 = "truncate cargo;";
            stm.executeUpdate(sql2);
           
             
            ResultSet rs = stm.executeQuery(sql);
          
           
            
            if(rs.next()){
                


                try{
                    
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
             
                Statement stm1 = con1.createStatement();

                String sql3= "select cargo from login where usuario='"+usuario+"' ";
                    
                ResultSet rs3 = stm1.executeQuery(sql3);
                    if (rs3.next()) {
                        int cargostr = rs3.getInt(1);
                        if(cargostr == 1){

                            try{
                    
                                Class.forName("com.mysql.cj.jdbc.Driver");
                                Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
                             
                                Statement stm3 = con2.createStatement();                                                                            
                                                                      
                                String sql4 = "select cargo from login where usuario='"+usuario+"' ";
                                     
                                ResultSet rs4 = stm3.executeQuery(sql4);
                                if (rs4.next()) {
                                    int numCargo = rs4.getInt(1);
                                String sql5 = "insert into cargo(cargo_numero) values('"+numCargo+"');";
                                stm.executeUpdate(sql5);
                                dispose();
                                HomePage homePageAdmin = new HomePage();
                                homePageAdmin.show();
                                con2.close();
                                    
                                }
                            
                           
                            }
                            catch(Exception e){System.out.println(e.getMessage());}
                            
                           
                            }else if(cargostr == 0){
                                try{
                                    Class.forName("com.mysql.cj.jdbc.Driver");
                                    Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
                                 
                                    Statement stm3 = con2.createStatement();                                                                                                                                         
                                        
                                    String sql4 = "select cargo from login where usuario='"+usuario+"' ";
                                         
                                    ResultSet rs4 = stm3.executeQuery(sql4);
                                    if (rs4.next()) {
                                        int numCargo = rs4.getInt(1);
                                    String sql5 = "insert into cargo(cargo_numero) values('"+numCargo+"');";
                                    stm.executeUpdate(sql5);

                                    dispose();
                                    HomePageFuncionario homePageFuncionario = new HomePageFuncionario();
                                    homePageFuncionario.show();
                                    con2.close();
                                    }
                                
                            

                        }catch(Exception e){System.out.println(e.getMessage());}
                    }
                    }                                        
                    }                                 
                
                catch(Exception e){System.out.println(e.getMessage());}}
            else{
                JOptionPane.showMessageDialog(this, "usuario ou senha errado.");
                caixaDeTxtUsuario.setText("");
                caixaDeTxtSenha.setText("");
            }
            
        con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }        
    }//GEN-LAST:event_btLoginActionPerformed

    private void caixaDeTxtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeTxtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaDeTxtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JPasswordField caixaDeTxtSenha;
    private javax.swing.JTextField caixaDeTxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
