/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius Marques
 */
public class RegistrarPage extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPage
     */
    public RegistrarPage() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
            java.sql.Statement st = con.createStatement();
            String query="select * from login";
            ResultSet rs=st.executeQuery(query);
            java.sql.ResultSetMetaData rsmd=rs.getMetaData();
        
            DefaultTableModel model= (DefaultTableModel) TableUsuarios.getModel();
            
            int cols = 1;
            String[] colName=new String[cols];
            for(int i=0;i<cols;i++){
                colName[i]=rsmd.getColumnName(i);
            model.setColumnIdentifiers(colName);}
            
            
            model.setColumnIdentifiers(colName);
        
            String usuario;
       
            
            while(rs.next()) {
                usuario=rs.getString(1);
     
                String[] row= {usuario};
                model.addRow(row);
                
            }             
            con.close();
            } 
            catch (ClassNotFoundException | SQLException e1){
                
            }

            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
                java.sql.Statement st = con.createStatement();
                String query="select * from login";
                ResultSet rs=st.executeQuery(query);
                java.sql.ResultSetMetaData rsmd=rs.getMetaData();
            
                DefaultTableModel model= (DefaultTableModel) TableUsuarios.getModel();
                
                int cols = 1;
                String[] colName=new String[cols];
                for(int i=0;i<cols;i++)
                    colName[i]=rsmd.getColumnName(i+2);
                model.setColumnIdentifiers(colName);
            
                String item;
                while(rs.next()) {
                    item=rs.getString(2);
                    String[] row= {item};
                    model.addRow(row);
                    
                }
                con.close();
                
                } 
                catch (ClassNotFoundException | SQLException e1){
                }          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btLogoff = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btRegistrar2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btCardapio = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btMesas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btHomePage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btExcluir = new javax.swing.JButton();
        caixaTxtRegistroUsuario = new javax.swing.JTextField();
        listaDeCargo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        caixaTxtRegistroSenha = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUsuarios = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        btRegistrar1 = new javax.swing.JButton();
        irAoRelatorio = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/linha reta divisao.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Restaurante");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 40));

        btLogoff.setBackground(new java.awt.Color(50, 27, 9));
        btLogoff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLogoff.setForeground(new java.awt.Color(255, 255, 255));
        btLogoff.setText("Logoff");
        btLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoffActionPerformed(evt);
            }
        });
        getContentPane().add(btLogoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btRegistrar2.setBackground(new java.awt.Color(68, 35, 4));
        btRegistrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegistrar2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btRegistrar2MousePressed(evt);
            }
        });
        btRegistrar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Registrar/Relatorio");
        btRegistrar2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 170, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Icone usuario.png"))); // NOI18N
        btRegistrar2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        jPanel3.add(btRegistrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 260, 50));

        btCardapio.setBackground(new java.awt.Color(68, 35, 4));
        btCardapio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCardapioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCardapioMousePressed(evt);
            }
        });
        btCardapio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Cardapio");
        btCardapio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 90, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Icone cardapio.png"))); // NOI18N
        btCardapio.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        jPanel3.add(btCardapio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 50));

        btMesas.setBackground(new java.awt.Color(68, 35, 4));
        btMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMesasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMesasMousePressed(evt);
            }
        });
        btMesas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Mesas");
        btMesas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Icone mesa 50x50.png"))); // NOI18N
        btMesas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        jPanel3.add(btMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 50));

        btHomePage.setBackground(new java.awt.Color(68, 35, 4));
        btHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHomePageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btHomePageMousePressed(evt);
            }
        });
        btHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(212, 212, 212));
        jLabel4.setText("Home");
        btHomePage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Icone home.png"))); // NOI18N
        btHomePage.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        jPanel3.add(btHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 50));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 10));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/alface.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 130, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/SideTab imagem.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 680));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Restaurante");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 673));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(204, 51, 0));
        btExcluir.setText("EXCLUIR");
        btExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel7.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 120, 55));

        caixaTxtRegistroUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caixaTxtRegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTxtRegistroUsuarioActionPerformed(evt);
            }
        });
        jPanel7.add(caixaTxtRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 240, 54));

        listaDeCargo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        listaDeCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garçom", "Gerente", " " }));
        listaDeCargo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listaDeCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeCargoActionPerformed(evt);
            }
        });
        jPanel7.add(listaDeCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 240, 53));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/linha reta divisao.png"))); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, -20, 10, 760));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cargo");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 60, 50));

        caixaTxtRegistroSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caixaTxtRegistroSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTxtRegistroSenhaActionPerformed(evt);
            }
        });
        jPanel7.add(caixaTxtRegistroSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 240, 50));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Usuário");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 70, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Logo usuario.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 100, 110));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Senha");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 60, 50));

        TableUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TableUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableUsuarios.setRowHeight(40);
        TableUsuarios.setRowMargin(10);
        jScrollPane1.setViewportView(TableUsuarios);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 310, 380));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/alface.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, -10, 150, 110));

        btRegistrar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btRegistrar1.setText("REGISTRAR");
        btRegistrar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrar1ActionPerformed(evt);
            }
        });
        jPanel7.add(btRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 120, 55));

        irAoRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        irAoRelatorio.setText("RELATORIO");
        irAoRelatorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        irAoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irAoRelatorioActionPerformed(evt);
            }
        });
        jPanel7.add(irAoRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 120, 60));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 400, 10));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 920, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoffActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.show();
        dispose();
    }//GEN-LAST:event_btLogoffActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int index = TableUsuarios.getSelectedRow();
        String selectedRowFromTbUsuarioTable = (String) TableUsuarios.getValueAt(index, 0);


        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
            java.sql.Statement st = con.createStatement();
            String query= "delete from login WHERE usuario='"+selectedRowFromTbUsuarioTable+"';";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");
            
            RegistrarPage regpag = new RegistrarPage();
                regpag.show();
                dispose();
            
            
            

        }
        catch (ClassNotFoundException | SQLException e1){
            System.out.println(e1);
        }

        

    }//GEN-LAST:event_btExcluirActionPerformed
        
    private void caixaTxtRegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void caixaTxtRegistroSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTxtRegistroSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTxtRegistroSenhaActionPerformed

    private void btRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrar1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
            
            String usuario = caixaTxtRegistroUsuario.getText();
            String senha = caixaTxtRegistroSenha.getText();
            Object cargo = listaDeCargo.getSelectedItem();
            String cargoString = cargo.toString();
            
            if(cargoString == "Gerente"){
                int x = 1;
                Statement stm = con.createStatement();
            
                if(usuario.length() <= 1  || senha.length() <= 1){
                JOptionPane.showMessageDialog(this, "Insira o usuario, senha e cargo corretamente!");
                con.close();
            }
            

            stm.executeUpdate("insert into login (usuario, senha, cargo)" + "values ('"+usuario+"', '"+senha+"','"+x+"');");
            
            
            JOptionPane.showMessageDialog(this, "Registro criado com sucesso!");
                      
           
            con.close();
            RegistrarPage regpag = new RegistrarPage();
            regpag.show();
            dispose();

            }else if(cargoString == "Garçom"){
                int y = 0;
                Statement stm = con.createStatement();
                
            
            if(usuario.length() <= 1  || senha.length() <= 1){
                JOptionPane.showMessageDialog(this, "Insira o usuario, senha e cargo corretamente!");
                con.close();
            }
            

            stm.executeUpdate("insert into login (usuario, senha, cargo)" + "values ('"+usuario+"', '"+senha+"','"+y+"');");
            
            
            JOptionPane.showMessageDialog(this, "Registro criado com sucesso!");
            RegistrarPage regpag = new RegistrarPage();
                regpag.show();
                dispose();
                   
           
            con.close();
            }
            
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btRegistrar1ActionPerformed

    private void irAoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irAoRelatorioActionPerformed
        // TODO add your handling code here:
        Relatorio relatorio = new Relatorio();
        relatorio.show();
        dispose();
    }//GEN-LAST:event_irAoRelatorioActionPerformed

    private void listaDeCargoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }   
    
    private void btHomePageMousePressed(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        setColor(btHomePage);
        resetColor(btMesas);
        resetColor(btCardapio);
        resetColor(btRegistrar2);   
    }                                       

    private void btMesasMousePressed(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        setColor(btMesas);
        resetColor(btHomePage);
        resetColor(btCardapio);
        resetColor(btRegistrar2);
    }                                    

    private void btCardapioMousePressed(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        setColor(btCardapio);
        resetColor(btHomePage);
        resetColor(btMesas);
        resetColor(btRegistrar2);
    }                                       

    private void btRegistrar2MousePressed(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        setColor(btRegistrar2);
        resetColor(btHomePage);
        resetColor(btMesas);
        resetColor(btCardapio);
    }                                        

    private void btHomePageMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.show();
        dispose();
    }                                       

    private void btMesasMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        MesasPage mesa = new MesasPage();
        mesa.show();
        dispose();
    }                                    

    private void btCardapioMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        CardapioPage cardapio = new CardapioPage();
        cardapio.show();
        dispose();
    }                                       

    private void btRegistrar2MouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        RegistrarPage registro = new RegistrarPage();
        registro.show();
        dispose();
    }                                        
                                
    void setColor(JPanel panel){
        panel.setBackground(new Color(90,46,9));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(68,35,4));
    }
    
    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPage().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableUsuarios;
    private javax.swing.JPanel btCardapio;
    private javax.swing.JButton btExcluir;
    private javax.swing.JPanel btHomePage;
    private javax.swing.JButton btLogoff;
    private javax.swing.JPanel btMesas;
    private javax.swing.JButton btRegistrar1;
    private javax.swing.JPanel btRegistrar2;
    private javax.swing.JPasswordField caixaTxtRegistroSenha;
    private javax.swing.JTextField caixaTxtRegistroUsuario;
    private javax.swing.JButton irAoRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> listaDeCargo;
    // End of variables declaration//GEN-END:variables
}
