/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicialDt = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatorioTb = new javax.swing.JTable();
        executarBt = new javax.swing.JButton();
        finalDt = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voltarBt = new javax.swing.JButton();
        limparBt = new javax.swing.JButton();
        valorTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(inicialDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 177, 44));

        relatorioTb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        relatorioTb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        relatorioTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        relatorioTb.setRowHeight(40);
        relatorioTb.setRowMargin(10);
        jScrollPane1.setViewportView(relatorioTb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 530, 410));

        executarBt.setBackground(new java.awt.Color(50, 27, 9));
        executarBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        executarBt.setForeground(new java.awt.Color(255, 255, 255));
        executarBt.setText("Executar");
        executarBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        executarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executarBtActionPerformed(evt);
            }
        });
        getContentPane().add(executarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 50));
        getContentPane().add(finalDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 177, 44));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data inicial:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data final :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, -1));

        voltarBt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        voltarBt.setText("Voltar");
        voltarBt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voltarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtActionPerformed(evt);
            }
        });
        getContentPane().add(voltarBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 120, 50));

        limparBt.setBackground(new java.awt.Color(50, 27, 9));
        limparBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        limparBt.setForeground(new java.awt.Color(255, 255, 255));
        limparBt.setText("Limpar");
        limparBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        limparBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtActionPerformed(evt);
            }
        });
        getContentPane().add(limparBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 430, 100, 50));

        valorTotal.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        valorTotal.setForeground(new java.awt.Color(255, 255, 255));
        valorTotal.setText("\"Valor total em reais :  R$\"+x");
        getContentPane().add(valorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/SideTab imagem.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executarBtActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dataInicial = sdf.format(inicialDt.getDate());
        String dataFinal = sdf.format(finalDt.getDate());
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
            java.sql.Statement st = con.createStatement();
            String query = "select * from storage where ts2 between '"+dataInicial+" 00:00:00' and '"+dataFinal+" 23:59:59';";
            
            ResultSet rs = st.executeQuery(query);
            ResultSetMetaData rsmd=rs.getMetaData();
            
            DefaultTableModel model=(DefaultTableModel) relatorioTb.getModel();
            
            int cols=rsmd.getColumnCount();
            String[] colName=new String[cols];
            for(int i=0;i<cols;i++)
                colName[i]=rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
            
            
            String id,ts2,item,preco;
            while(rs.next()){
                id=rs.getString(1);
                ts2=rs.getString(2);
                item=rs.getString(3);
                preco=rs.getString(4);
                String[] row= {id,ts2,item,preco};
                model.addRow(row);
            }
         
            
            
            
            
            
         
         
         }catch (ClassNotFoundException | SQLException e1){
            System.out.println(e1);}
        
    }//GEN-LAST:event_executarBtActionPerformed

    private void limparBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtActionPerformed
          // TODO add your handling code here:
          relatorioTb.setModel(new DefaultTableModel());
    }//GEN-LAST:event_limparBtActionPerformed

    private void voltarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtActionPerformed
        // TODO add your handling code here:
        HomePage page = new HomePage();
        page.show();
        dispose();
    }//GEN-LAST:event_voltarBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executarBt;
    private com.toedter.calendar.JDateChooser finalDt;
    private com.toedter.calendar.JDateChooser inicialDt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparBt;
    private javax.swing.JTable relatorioTb;
    private javax.swing.JLabel valorTotal;
    private javax.swing.JButton voltarBt;
    // End of variables declaration//GEN-END:variables
}
