/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto.Mesas;

import Projeto.Funcionario.HomePageFuncionario;
import Projeto.Funcionario.MesasPageFuncionario;
import Projeto.HomePage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Projeto.MesasPage;
import java.sql.Statement;

/**
 *
 * @author Vinicius Marques
 */
public class DentroMesa5 extends javax.swing.JFrame {

    /**
     * Creates new form DentroMesa5
     */
    public DentroMesa5() {
        initComponents();
       try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
            java.sql.Statement st = con.createStatement();
            String query="select * from mesa5";
            ResultSet rs=st.executeQuery(query);
            java.sql.ResultSetMetaData rsmd=rs.getMetaData();
        
            DefaultTableModel model= (DefaultTableModel) tableItensMesa5.getModel();
            
            int cols = 1;
            String[] colName=new String[cols];
            for(int i=0;i<cols;i++)
                colName[i]=rsmd.getColumnName(i+1);
            model.setColumnIdentifiers(colName);
        
            String item;
            while(rs.next()) {
                item=rs.getString(1);
                String[] row= {item};
                model.addRow(row);
                                
            }
        
            
            } 
            catch (ClassNotFoundException | SQLException e1){
                
            }


            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
                java.sql.Statement st = con.createStatement();
                String query="select * from menu";
                ResultSet rs=st.executeQuery(query);
                java.sql.ResultSetMetaData rsmd=rs.getMetaData();
            
                DefaultTableModel model= (DefaultTableModel) tableItensMenu5.getModel();
                
                int cols = 1;
                String[] colName=new String[cols];
                for(int i=0;i<cols;i++)
                    colName[i]=rsmd.getColumnName(i+1);
                model.setColumnIdentifiers(colName);
            
                String item;
                while(rs.next()) {
                    item=rs.getString(1);
                    String[] row= {item};
                    model.addRow(row);
                  
                    
                }
              
                
                } 
                catch (ClassNotFoundException | SQLException e1){
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItensMesa5 = new javax.swing.JTable();
        btAdd5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableItensMenu5 = new javax.swing.JTable();
        btPagar5 = new javax.swing.JButton();
        btVoltar5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MESA 5");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 70, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ITENS DO CARDÁPIO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ITENS DA MESA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 120, 50));

        tableItensMesa5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tableItensMesa5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItensMesa5.setRowHeight(30);
        tableItensMesa5.setRowMargin(5);
        jScrollPane2.setViewportView(tableItensMesa5);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 310, 390));

        btAdd5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btAdd5.setText("ADICIONAR");
        btAdd5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAdd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdd5ActionPerformed(evt);
            }
        });
        jPanel1.add(btAdd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 130, 50));

        tableItensMenu5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tableItensMenu5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItensMenu5.setRowHeight(30);
        tableItensMenu5.setRowMargin(5);
        jScrollPane3.setViewportView(tableItensMenu5);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, 390));

        btPagar5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btPagar5.setText("PAGAR");
        btPagar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btPagar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagar5ActionPerformed(evt);
            }
        });
        jPanel1.add(btPagar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 130, 50));

        btVoltar5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btVoltar5.setText("VOLTAR");
        btVoltar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btVoltar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar5ActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 130, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/alface invertido.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -20, 180, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Batata frita.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 270, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/imagem botao mesas.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -10, 340, 570));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/imagem botao mesas.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 550, 570));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/imagem botao mesas.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 550, 570));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/imagem botao mesas.png"))); // NOI18N
        jLabel5.setText("jLabel1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 340, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdd5ActionPerformed
        // TODO add your handling code here:
         int index = tableItensMenu5.getSelectedRow();
        String selectedRowFromTbMenu5 = (String) tableItensMenu5.getValueAt(index, 0);
        

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
            java.sql.Statement st = con.createStatement();
            String query= "INSERT INTO mesa5 SELECT item,preco FROM menu WHERE item='"+selectedRowFromTbMenu5+"';";
            String query2= "INSERT INTO storage(item,preco) select item, preco FROM menu WHERE item='"+selectedRowFromTbMenu5+"';";
            String query3="SELECT id FROM storage WHERE id=(SELECT max(id) FROM storage);";
            
            st.executeUpdate(query);
            st.executeUpdate(query2);
            ResultSet rs=st.executeQuery(query3);
            if(rs.next()){
                int idParaData = rs.getInt(1);
                String query4 = "UPDATE storage SET ts2 = now() WHERE id='"+idParaData+"';";
                st.executeUpdate(query4);
                

            } 
            
            

        }
        catch (ClassNotFoundException | SQLException e1){
            System.out.println(e1);
        }
        DentroMesa5 mesa5 = new DentroMesa5();
        mesa5.show();
        dispose();
    }//GEN-LAST:event_btAdd5ActionPerformed

    private void btPagar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagar5ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
            java.sql.Statement st = con.createStatement();
            String query= "SELECT ROUND(SUM(preco), 2) FROM mesa5;";
            ResultSet rs=st.executeQuery(query);
           while(rs.next()){
               Float valorMesa5 = rs.getFloat(1);
               JOptionPane.showMessageDialog(this, "Valor a ser pago:R$"+valorMesa5+"!");
               String query2 = "TRUNCATE mesa5;";
               st.executeUpdate(query2);
               DentroMesa5 mesa5 = new DentroMesa5();
                       mesa5.show();
                       dispose();
           }
            
            con.close();

        }
        catch (ClassNotFoundException | SQLException e1){
            System.out.println(e1);




        
    }       
    }//GEN-LAST:event_btPagar5ActionPerformed

    private void btVoltar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar5ActionPerformed
        // TODO add your handling code here:
          try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurante_login","root","12345678vini@");
            
            Statement stm3 = con2.createStatement();

            String sql4 = "select cargo_numero from cargo; ";
                    
            ResultSet rs4 = ((java.sql.Statement) stm3).executeQuery(sql4);

            if (rs4.next()) {
                int numCargo = rs4.getInt(1);
                if(numCargo == 1){
                    dispose();
                    MesasPage mesasPageAdmin = new MesasPage();
                    mesasPageAdmin.show();
                }else if(numCargo == 0){
                    dispose();
                    MesasPageFuncionario mesasPageFuncionario = new MesasPageFuncionario();
                    mesasPageFuncionario.show();
                }               
            }

        }
        catch (ClassNotFoundException | SQLException e1){
            System.out.println(e1);
        }
    }//GEN-LAST:event_btVoltar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DentroMesa5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DentroMesa5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DentroMesa5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DentroMesa5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DentroMesa5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd5;
    private javax.swing.JButton btPagar5;
    private javax.swing.JButton btVoltar5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableItensMenu5;
    private javax.swing.JTable tableItensMesa5;
    // End of variables declaration//GEN-END:variables
}
