/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto.Funcionario;

import Projeto.Login;
import Projeto.CardapioPage;
import Projeto.Login;
import Projeto.Mesas.DentroMesa1;
import Projeto.Mesas.DentroMesa2;
import Projeto.Mesas.DentroMesa3;
import Projeto.Mesas.DentroMesa4;
import Projeto.Mesas.DentroMesa5;
import Projeto.Mesas.DentroMesa6;
import Projeto.MesasPage;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Vinicius Marques
 */
public class MesasPageFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form MesasPageFuncionario
     */
    public MesasPageFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btLogoff = new javax.swing.JButton();
        btCardapioFuncionario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btMesasFuncionario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btHomePageFuncionario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mesa06 = new javax.swing.JButton();
        mesa01 = new javax.swing.JButton();
        mesa02 = new javax.swing.JButton();
        mesa03 = new javax.swing.JButton();
        mesa04 = new javax.swing.JButton();
        mesa05 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Restaurante");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 40));

        btLogoff.setBackground(new java.awt.Color(50, 27, 9));
        btLogoff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btLogoff.setForeground(new java.awt.Color(255, 255, 255));
        btLogoff.setText("Logoff");
        btLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoffActionPerformed(evt);
            }
        });
        jPanel3.add(btLogoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 80, 40));

        btCardapioFuncionario.setBackground(new java.awt.Color(68, 35, 4));
        btCardapioFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCardapioFuncionarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCardapioFuncionarioMousePressed(evt);
            }
        });
        btCardapioFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Cardapio");
        btCardapioFuncionario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Icone cardapio.png"))); // NOI18N
        btCardapioFuncionario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        jPanel3.add(btCardapioFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 50));

        btMesasFuncionario.setBackground(new java.awt.Color(68, 35, 4));
        btMesasFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMesasFuncionarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMesasFuncionarioMousePressed(evt);
            }
        });
        btMesasFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Mesas");
        btMesasFuncionario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Icone mesa 50x50.png"))); // NOI18N
        btMesasFuncionario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        jPanel3.add(btMesasFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 260, 50));

        btHomePageFuncionario.setBackground(new java.awt.Color(68, 35, 4));
        btHomePageFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btHomePageFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHomePageFuncionarioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btHomePageFuncionarioMousePressed(evt);
            }
        });
        btHomePageFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(212, 212, 212));
        jLabel4.setText("Home");
        btHomePageFuncionario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 60, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Icone home.png"))); // NOI18N
        btHomePageFuncionario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jPanel3.add(btHomePageFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 50));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/SideTab imagem.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 680));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Restaurante");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        mesa06.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mesa06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/icone mesa 100x100.png"))); // NOI18N
        mesa06.setText("Mesa 06");
        mesa06.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mesa06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa06ActionPerformed(evt);
            }
        });
        jPanel2.add(mesa06);
        mesa06.setBounds(630, 360, 210, 133);

        mesa01.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mesa01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/icone mesa 100x100.png"))); // NOI18N
        mesa01.setText("Mesa 01");
        mesa01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mesa01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa01ActionPerformed(evt);
            }
        });
        jPanel2.add(mesa01);
        mesa01.setBounds(100, 160, 220, 133);

        mesa02.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mesa02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/icone mesa 100x100.png"))); // NOI18N
        mesa02.setText("Mesa 02");
        mesa02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mesa02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa02ActionPerformed(evt);
            }
        });
        jPanel2.add(mesa02);
        mesa02.setBounds(370, 160, 210, 133);

        mesa03.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mesa03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/icone mesa 100x100.png"))); // NOI18N
        mesa03.setText("Mesa 03");
        mesa03.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mesa03.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mesa03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa03ActionPerformed(evt);
            }
        });
        jPanel2.add(mesa03);
        mesa03.setBounds(630, 160, 210, 133);

        mesa04.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mesa04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/icone mesa 100x100.png"))); // NOI18N
        mesa04.setText("Mesa 04");
        mesa04.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mesa04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa04ActionPerformed(evt);
            }
        });
        jPanel2.add(mesa04);
        mesa04.setBounds(100, 360, 220, 133);

        mesa05.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mesa05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/icone mesa 100x100.png"))); // NOI18N
        mesa05.setText("Mesa 05");
        mesa05.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mesa05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesa05ActionPerformed(evt);
            }
        });
        jPanel2.add(mesa05);
        mesa05.setBounds(370, 360, 210, 133);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Molho.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(210, 600, 110, 80);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/Batata frita.png"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(-50, 110, 260, 570);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/imagens/samabaia.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(530, -10, 440, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoffActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.show();
        dispose();
    }//GEN-LAST:event_btLogoffActionPerformed

    private void btCardapioFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCardapioFuncionarioMouseClicked
        // TODO add your handling code here:
        CardapioPageFuncionario cardapio = new CardapioPageFuncionario();
        cardapio.show();
        dispose();
    }//GEN-LAST:event_btCardapioFuncionarioMouseClicked

    private void btCardapioFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCardapioFuncionarioMousePressed
        // TODO add your handling code here
       setColor(btCardapioFuncionario);
       resetColor(btHomePageFuncionario);
       resetColor(btMesasFuncionario); 
    }//GEN-LAST:event_btCardapioFuncionarioMousePressed

    private void btMesasFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMesasFuncionarioMouseClicked
        // TODO add your handling code here:
        MesasPageFuncionario mesa = new MesasPageFuncionario();
        mesa.show();
        dispose();
    }//GEN-LAST:event_btMesasFuncionarioMouseClicked

    private void btMesasFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMesasFuncionarioMousePressed
        // TODO add your handling code here:
        setColor(btMesasFuncionario);
        resetColor(btHomePageFuncionario);
        resetColor(btCardapioFuncionario);
    }//GEN-LAST:event_btMesasFuncionarioMousePressed

    private void btHomePageFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHomePageFuncionarioMouseClicked
        // TODO add your handling code here:
        HomePageFuncionario homeFuncionario = new HomePageFuncionario();
        homeFuncionario.show();
        dispose();
    }//GEN-LAST:event_btHomePageFuncionarioMouseClicked

    private void btHomePageFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHomePageFuncionarioMousePressed
        // TODO add your handling code here:
        setColor(btHomePageFuncionario);
        resetColor(btMesasFuncionario);
        resetColor(btCardapioFuncionario);  
    }//GEN-LAST:event_btHomePageFuncionarioMousePressed

    private void mesa06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa06ActionPerformed
        // TODO add your handling code here:
        DentroMesa6 mesa = new DentroMesa6();
        mesa.show();
        dispose();
    }//GEN-LAST:event_mesa06ActionPerformed

    private void mesa01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa01ActionPerformed
        // TODO add your handling code here:
        DentroMesa1 mesa = new DentroMesa1();
        mesa.show();
        dispose();
    }//GEN-LAST:event_mesa01ActionPerformed

    private void mesa02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa02ActionPerformed
        // TODO add your handling code here:
        DentroMesa2 mesa = new DentroMesa2();
        mesa.show();
        dispose();
    }//GEN-LAST:event_mesa02ActionPerformed

    private void mesa03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa03ActionPerformed
        // TODO add your handling code here:
        DentroMesa3 mesa = new DentroMesa3();
        mesa.show();
        dispose();
    }//GEN-LAST:event_mesa03ActionPerformed

    private void mesa04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa04ActionPerformed
        // TODO add your handling code here:
        DentroMesa4 mesa = new DentroMesa4();
        mesa.show();
        dispose();
    }//GEN-LAST:event_mesa04ActionPerformed

    private void mesa05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesa05ActionPerformed
        // TODO add your handling code here:
        DentroMesa5 mesa = new DentroMesa5();
        mesa.show();
        dispose();
    }//GEN-LAST:event_mesa05ActionPerformed

    void setColor(JPanel panel){
        panel.setBackground(new Color(90,46,9));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(68,35,4));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MesasPageFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MesasPageFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MesasPageFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MesasPageFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MesasPageFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btCardapioFuncionario;
    private javax.swing.JPanel btHomePageFuncionario;
    private javax.swing.JButton btLogoff;
    private javax.swing.JPanel btMesasFuncionario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mesa01;
    private javax.swing.JButton mesa02;
    private javax.swing.JButton mesa03;
    private javax.swing.JButton mesa04;
    private javax.swing.JButton mesa05;
    private javax.swing.JButton mesa06;
    // End of variables declaration//GEN-END:variables
}
